<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="1"
            tests="1">

  <testsuite name="test"
    errors="0" failures="1" hostname="" id="" package="test" skipped="0"
    tests="1" time="17.77" timestamp="Fri, 22 Jul 2016 01:06:37 GMT">
  
    <testcase name="default e2e tests" time="17.77" assertions="4">

    

    

      <failure message="Testing if element &lt;input&gt; has count: 3">    at Object.module.exports.default e2e tests (/home/scc/work/passport_fe/static/test/e2e/specs/test.js:11:15)
    at Module.call (/home/scc/work/passport_fe/static/node_modules/nightwatch/lib/runner/module.js:63:34)
    at /home/scc/work/passport_fe/static/node_modules/nightwatch/lib/runner/testcase.js:97:29
    at _fulfilled (/home/scc/work/passport_fe/static/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/scc/work/passport_fe/static/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/scc/work/passport_fe/static/node_modules/q/q.js:796:13)
    at /home/scc/work/passport_fe/static/node_modules/q/q.js:556:49
    at runSingle (/home/scc/work/passport_fe/static/node_modules/q/q.js:137:13)
    at flush (/home/scc/work/passport_fe/static/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)</failure>

    
    </testcase>
  
  
  </testsuite>
</testsuites>
